name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./author/pom.xml
          mvn clean package -f ./aiservice/pom.xml
          mvn clean package -f ./platform/pom.xml
          mvn clean package -f ./writing/pom.xml
          mvn clean package -f ./point/pom.xml

      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Author
        uses: docker/build-push-action@v4
        with:
          context: ./author
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/author:latest
            ghcr.io/${{ github.repository }}/author:${{ github.ref_name }}
            
      - name: Docker Build and push for Aiservice
        uses: docker/build-push-action@v4
        with:
          context: ./aiservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/aiservice:latest
            ghcr.io/${{ github.repository }}/aiservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Platform
        uses: docker/build-push-action@v4
        with:
          context: ./platform
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/platform:latest
            ghcr.io/${{ github.repository }}/platform:${{ github.ref_name }}
            
      - name: Docker Build and push for Writing
        uses: docker/build-push-action@v4
        with:
          context: ./writing
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/writing:latest
            ghcr.io/${{ github.repository }}/writing:${{ github.ref_name }}
            
      - name: Docker Build and push for Point
        uses: docker/build-push-action@v4
        with:
          context: ./point
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/point:latest
            ghcr.io/${{ github.repository }}/point:${{ github.ref_name }}
            
