server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, /viewSubscriptionHistories/**, /viewReadingHistories/**, /viewSubscriptionHistories/**, /viewContectHistories/**
        - id: author
          uri: http://localhost:8083
          predicates:
            - Path=/authors/**, /publicationStatuses/**
        - id: aiservice
          uri: http://localhost:8084
          predicates:
            - Path=/bookWorks/**, 
        - id: platform
          uri: http://localhost:8085
          predicates:
            - Path=/books/**, /bookViews/**, 
        - id: writing
          uri: http://localhost:8086
          predicates:
            - Path=/manuscripts/**, /manuscriptLists/**
        - id: point
          uri: http://localhost:8087
          predicates:
            - Path=/points/**, /pointInquiries/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/authors/**, 
        - id: aiservice
          uri: http://aiservice:8080
          predicates:
            - Path=/bookWorks/**, 
        - id: platform
          uri: http://platform:8080
          predicates:
            - Path=/books/**, /bookViews/**, 
        - id: writing
          uri: http://writing:8080
          predicates:
            - Path=/manuscripts/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
